# - name: GitHub Action for DigitalOcean - doctl
#   uses: digitalocean/action-doctl@v2.1.0
#   with:
#     token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}

name: deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          source: "app"
          target: "app/alltru"

      - name: Run app
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd app/alltru
            npm run build
            pm2 start